license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MysticalAgradditions/issues"
    modId="mysticalagradditions"
    version="${mod_version}"
    displayName="Mystical Agradditions"
    updateJSONURL="https://api.blakesmods.com/v2/mods/mysticalagradditions/26.1/updates"
    displayURL="https://blakesmods.com/mystical-agradditions"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="Mark719, xun468"
    description='''
    Grow all your resources!
    '''

    [[dependencies.mysticalagradditions]]
        modId="neoforge"
        mandatory=true
        versionRange="[26.1.2.41-beta,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalagradditions]]
        modId="minecraft"
        mandatory=true
        versionRange="[26.1.2,26.2)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalagradditions]]
        modId="cucumber"
        mandatory=true
        versionRange="[${cucumber_version},)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalagradditions]]
        modId="mysticalagriculture"
        mandatory=true
        versionRange="[${mysticalagriculture_version},)"
        ordering="AFTER"
        side="BOTH"